#!/bin/bash

if [[ $1 = "" ]]; then
  echo "no tag"
  exit
fi

rm -rf dist
mkdir -p dist

export CGO_ENABLED=0
export GOOS=linux
export GOARCH=amd64
go build -ldflags '-w' -o dist/server start.go

cp *.yml dist/
cp -r www dist/

scp -r dist root@192.168.1.140:/tmp/hub
scp -r Dockerfile root@192.168.1.140:/tmp/hub

ssh root@192.168.1.140 "cd /tmp/hub && docker build --network=host . -t ssgo/hub:$1"
